### ISSUE TITLE
[GUIDE] 스타일 지정

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/Charo-Design#1]
## 📌 Title

스타일을 지정합니다 

## 📝  To-do

- [ ] 할일 쓰기 그리고 엔터하
- [x]  그라데이션
- [x]  그림자
- [x]  색상
- [x]  텍스트 스타일
    태그 세개는 컴포넌트 만든 후 한번에 적용하겠습니다~!
- [x]  구경하기 메인뷰
- [x]  메인뷰/게시물 더보기
- [x]  상세 게시물 페이지
- [x]  메인뷰/테마
- [x]  작성하기(빈화면)
- [x]  작성하기(과정)
- [x]  작성하기/지도 입력
- [x]  작성하기/ 완료전 페이지
- [x]  작성하기/ 완료 화면
