### ISSUE TITLE
[GUI] 마이페이지 뷰

### ISSUE THREAD

**Issue by yeosulee** [TeamChaRo/Charo-Design#10]
## 📌 Title
마이페이지_릴리즈

## 📝  To-do
- 나의 차로 (마이페이지) → 8월 3째주 (~8월 22일)
- [x]  등급 부여 삭제
- [ ]  팔로워/ 팔로잉
    - [ ]  팔로워 팔로잉 위치 반전
    - [ ]  팔로잉 리스트뷰 (본인 페이지에서)
    - [ ]  팔로잉 리스트뷰_ 팔로우 취소 보여주는 뷰 (팔로우로)
    - [ ]  팔로워 리스트뷰 (본인)
- [ ]  설정 *후순위
    - [ ]  (푸시알림 동의 추가)
    - [ ]  비밀번호 재설정
- 타 유저(A)의 마이페이지 → 8월 3째주 (~8월 22일)
- [ ]  타유저 마이페이지
    - [ ]  A가 좋아요한 게시물은 안보이게
    - [ ]  팔로우 버튼 추가
- [ ]  팔로잉 리스트뷰
- [ ]  팔로워 리스트뷰
