### ISSUE TITLE
[GUI] 로그인/회원가입 뷰

### ISSUE THREAD

**Issue by yeosulee** [TeamChaRo/Charo-Design#11]
## 📌 Title
로그인/회원가입 뷰_릴리즈

## 📝  To-do
- 로그인/회원가입 → 8월 3째주 (~8월 22일)
- [ ]  비회원 둘러보기 버튼(?) 추가
- [ ]  로그인 해야할 경우 모달형식의 로그인뷰
- [ ]  로그인 및 회원가입 (카카오/애플/구글/이메일)
    - [ ]  로그인 뷰 수정
        - [ ]  약관 동의뷰 추후 수정
    - [ ]  회원가입 수정 (아이디 빠짐 + 워딩 수정)
    - [ ]  아이디 찾기
    - [ ]  비밀번호 찾기
