### ISSUE TITLE
[Timeline] 기능명세서 바탕으로 타임라인 짜기 

### ISSUE THREAD

**Issue by yeosulee** [TeamChaRo/Charo-Design#5]
## 📌 Title
기능명세서 바탕으로 타임라인 짜기 

## 📝  To-do

- [x] 구경하기 상세페이지 작업 날짜 정하기
- [x] 메인배너 연결 뷰 의논/ 작업 날짜
- [x] 나머지 뷰들 역할 분담하기
