### ISSUE TITLE
[GUI] 추가 및 수정할 뷰 최종정리

### ISSUE THREAD

**Issue by yeosulee** [TeamChaRo/Charo-Design#7]
## 📝  To-do
8월 31일까지 뷰 전체 완성 목표로..! 🙈

- [ ]  드롭박스로 선택해야하는  경우(인기순/최신순) → 바탕이 어둡게 변하게
- 8월 4째주 (~8월 29일) + @ (최대한 9월 첫째주 내로)
- [ ]  배너 이미지 클릭시 랜딩되는 상세페이지 디자인 *후순위 (먼저 줄지, 수정을 먼저 할지) → 일주일,,걸릴듯
- [ ]  온보딩
    - [ ]  구경하기, 작성하기 텍스트 줄이기
    - [ ]  디자인 수정
- 앱 진입 → 8월 4째주 (~8월 29일)
- [ ]  스플래시 → 길이 1초 정도로
- [ ]  로딩애니메이션 반영필요
- 로그인/회원가입 → 8월 3째주 (~8월 22일)
- [ ]  비회원 둘러보기 버튼(?) 추가
- [ ]  로그인 해야할 경우 모달형식의 로그인뷰
- [ ]  로그인 및 회원가입 (카카오/애플/구글/이메일)
    - [ ]  로그인 뷰 수정
        - [ ]  약관 동의뷰 추후 수정
    - [ ]  회원가입 수정 (아이디 빠짐 + 워딩 수정)
    - [ ]  아이디 찾기
    - [ ]  비밀번호 찾기
- 구경하기 → 8월 8일!, 8월 2째주 (~8월 15일)
- [ ]  전체 해시태그 빼기!!!
- [x]  메인 페이지 워딩 수정
- [ ]  구경하기 리스트뷰에서 개수 삭제 (전체 리스트뷰)
- [ ]  테마
    - [x]  이미지 방식 논의
    - [x]  # 빼기
- [ ]  구경하기 상세페이지 →"8월 12일 목 끝내기 목표" (2시~5시)
    - [x]  네오모피즘 디자인에서 변경된 GUI 논의
    - [x]  이미지 개수를 알 수 있는 인디케이터(점점점, 숫자)
    - [x]  공유하기 버튼 추가 → 좋아요, 공유, 저장이 한세트로
    - [ ]  이미지 전체 보여주는 방식필요! (개발자랑도 이야기 필요)
    - [ ]  좋아요 개수를 누를 시 좋아요한 사람 리스트 보여주기 → 팔로우 유무도 보여져야함
    - [x]  네비게이션 연동 버튼 필요
- 검색 → 8월 4째주 (~8월 29일)
- [ ]  오늘 드라이브는 옆에 3가지 요소 모두 입력할 필요 없다는 문구 추가
- [ ]  워딩 수정 (피그마 참고)
- 알림 → 8월 4째주 (~8월 29일)
- [ ]  알림
    - [ ]  최종 결정된 알림 메세지 대로 수정 (워딩 수정)
    - [ ]  팔로잉 관련 아이콘은 행동을 취한 사용자 프로필 사진으로 수정
- 작성하기 → 8월 4째주 (~8월 29일)
- [ ]  경로입력
    - [ ]  첫 화면 (지도 부분,, 위에 팝업 메세지!) 구성 수정
    - [ ]  워딩 수정 (글 부분)
    - [ ]  테마_ 모달뷰 (이미 선택된거 회색)
    - [ ]  경유지 추가 버튼 좀 더 잘 보이게 수정
- [ ]  팝업 창
    - [ ]  삭제한 부분 체크
        - [ ]  최종 등록시 작성이 완료되었다는 팝업 삭제
    - [ ]  추가한 부분 체크
        - [ ]  필수 작성란 안채웠을때 뜨는 팝업 추가 (글 작성페이지)
- 나의 차로 (마이페이지) → 8월 3째주 (~8월 22일)
- [x]  등급 부여 삭제
- [ ]  팔로워/ 팔로잉
    - [ ]  팔로워 팔로잉 위치 반전
    - [ ]  팔로잉 리스트뷰 (본인 페이지에서)
    - [ ]  팔로잉 리스트뷰_ 팔로우 취소 보여주는 뷰 (팔로우로)
    - [ ]  팔로워 리스트뷰 (본인)
- [ ]  설정 *후순위
    - [x]  (푸시알림 동의 추가)
    - [ ]  비밀번호 재설정
- 타 유저(A)의 마이페이지 → 8월 3째주 (~8월 22일)
- [ ]  타유저 마이페이지
    - [ ]  A가 좋아요한 게시물은 안보이게
    - [ ]  팔로우 버튼 추가
- [ ]  팔로잉 리스트뷰
- [ ]  팔로워 리스트뷰
