### ISSUE TITLE
[GUI] 구경하기 뷰

### ISSUE THREAD

**Issue by yeosulee** [TeamChaRo/Charo-Design#8]
## 📌 Title
<구경하기_릴리즈>

## 📝  To-do
- 구경하기 → 8월 8일!, 8월 2째주 (~8월 15일)
- [O]  전체 해시태그 빼기!!!
- [x]  메인 페이지 워딩 수정
- [O]  구경하기 리스트뷰에서 개수 삭제 (전체 리스트뷰)
- [O]  테마
    - [논의중]  이미지 방식 논의
    - [O]  # 빼기
- [ ]  구경하기 상세페이지 →"8월 12일 목 끝내기 목표" (2시~5시)
    - [O]  네오모피즘 디자인에서 변경된 GUI 논의
    - [O]  이미지 개수를 알 수 있는 인디케이터(점점점, 숫자)
    - [O]  공유하기 버튼 추가 → 좋아요, 공유, 저장이 한세트로
    - [논의]  이미지 전체 보여주는 방식필요! (개발자랑도 이야기 필요)
    - [O]  좋아요 개수를 누를 시 좋아요한 사람 리스트 보여주기 → 팔로우 유무도 보여져야함
    - [O]  네비게이션 연동 버튼 필요
- [ ]  안드 논의 끝나면 제플린 업데이트
